# Generated by Django 5.0.6 on 2024-07-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='usernname',
            new_name='username',
        ),
    ]
